#!/bin/bash
src="$(dirname "$0")"
IPV4_REGEX='([0-9]{1,3}\.){3}([0-9]{1,3})'
IPV6_REGEX='(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))'

if ipv6_gw=$("$src/gateway" -6); then
  >&2 echo "Default gateway exists in main routing table: $ipv6_gw"
  >&2 echo "Manually renewing the lifetime to 1800s..."
else
  ipv6_gw=$(rdisc6 -1 enp1s0 | grep '^ from' | grep -Eo "$IPV6_REGEX")
  if [ $? -ne 0 ]; then
    >&2 echo 'Unable to find a gateway, either from `ip route`' \
      'or from router solicitation'
    exit 1
  fi
  >&2 echo "Default gateway retrieved using router solicitation: $ipv6_gw"
  >&2 echo "Adding default route..."
fi

ip -6 r replace \
  default via "$ipv6_gw" dev enp1s0 proto ra \
  metric 1024 expires 1800 mtu 1500 pref medium
exit $?
